### ISSUE TITLE
Transitional probability computation

### ISSUE THREAD

**Issue by fullbat** [mattcieslak/MITTENS#2]
Hi,
in the "get_transition_analysis_matrices" method inside utils. py , shouldn't the odf_vertices variable be transposed to compute the pairwise distances?
The edges probabilities in the graph doesn't match the dsi-studio output and in general the diffusion data.   

Thank you

**Comment by mattcieslak** [comment]
Hi,

You're right, if look at where that function is called it is using the transposed odf_vertices variable. Here is where that currently happens: https://github.com/mattcieslak/MITTENS/blob/7721fbe4325964ce2ca3ce7cf40e919e29133816/mittens/utils.py#L129.

What do you mean by the second point?
