### ISSUE TITLE
voxel_graph.build_atlas_graph() results in networkit attribute error

### ISSUE THREAD

**Issue by unimusic** [mattcieslak/MITTENS#5]
When following the README example, calling voxel_graph.build_atlas_graph() results in the following error message:
*** AttributeError: module 'networkit.graph' has no attribute 'Dijkstra'

**Comment by mattcieslak** [comment]
Could you try updating mittens?

**Comment by mattcieslak** [comment]
nevermind, networkit changed their api. I will update and let you know
