### ISSUE TITLE
Installing MITTENS - Ubuntu or Google Colab

### ISSUE THREAD

**Issue by dubergonzoni** [mattcieslak/MITTENS#9]
Dear @mattcieslak,

In my Ubuntu 20.04 I can't install MITTENS. I got the following error:

$ cd MITTENS
$ pip install -e .

error: extension 'mittens.fortran.singleODF_odf8_ss0_87_am35' has Fortran sources but no Fortran compiler found

Using colab I could install:

!pip install -e drive/MyDrive/Research/ShortestPathTools/MITTENS

ps: here, MITTENS is inside ShortestPatthTools folder, but I have tried with MITTENS in another locations;

Obtaining file:///content/drive/MyDrive/Research/ShortestPathTools/MITTENS
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from mittens==0.0.0) (1.19.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from mittens==0.0.0) (0.22.2.post1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from mittens==0.0.0) (4.41.1)
Collecting networkit
  Downloading https://files.pythonhosted.org/packages/58/7a/4ef04f2b34fc81c5f2a5060b5cb989509f847d8aa6e359899922acffacf8/networkit-8.1.tar.gz (3.1MB)
     |████████████████████████████████| 3.1MB 8.0MB/s 
Requirement already satisfied: nibabel in /usr/local/lib/python3.7/dist-packages (from mittens==0.0.0) (3.0.2)
Collecting dipy
  Downloading https://files.pythonhosted.org/packages/50/50/0b97f4ecf9b02170c4967053c34a0c08373e538295c119aadffe8d5ff235/dipy-1.4.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (7.7MB)
     |████████████████████████████████| 7.7MB 12.9MB/s 
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->mittens==0.0.0) (1.0.1)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->mittens==0.0.0) (1.4.1)
Requirement already satisfied: h5py>=2.5.0 in /usr/local/lib/python3.7/dist-packages (from dipy->mittens==0.0.0) (3.1.0)
Requirement already satisfied: cached-property; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from h5py>=2.5.0->dipy->mittens==0.0.0) (1.5.2)
Building wheels for collected packages: networkit
  Building wheel for networkit (setup.py) ... done
  Created wheel for networkit: filename=networkit-8.1-cp37-cp37m-linux_x86_64.whl size=8069839 sha256=00570305f6cfee426bf6b50057cc1b4884324b0a66f13be0b79000f0134c6921
  Stored in directory: /root/.cache/pip/wheels/25/7e/59/6b58f6984b823663f6d01266ecb0306ce3d74d040acd27a818
Successfully built networkit
Installing collected packages: networkit, dipy, mittens
  Running setup.py develop for mittens
Successfully installed dipy-1.4.1 mittens networkit-8.1

Bu I can't import mittens:

from mittens import MITTENS

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-33-a7d27515427b> in <module>()
----> 1 from mittens import MITTENS

ModuleNotFoundError: No module named 'mittens'

My goal is to build a voxel graph to use with ShortestPathTool.

Thank you in advance.
Eduardo

**Comment by mattcieslak** [comment]
hello! Is it possible that your `pip` is installing to a different python installation? if you check with `which pip` it should show you which one you're using

**Comment by dubergonzoni** [comment]
Thank you for you quickly reply.

I've tried using anaconda and pyenv python installations:
$ which pip
/home/edu_asus/anaconda3/bin/pip

$ which pip
/home/edu_asus/.pyenv/shims/pip

Sorry for the confusion, but which python installation I have to use?

**Comment by dubergonzoni** [comment]
I have also tried with python from my system, but got the same error:

error: extension 'mittens.fortran.singleODF_odf8_ss0_87_am35' has Fortran sources but no Fortran compiler found

$ which python
/usr/bin/python

**Comment by dubergonzoni** [comment]
I also tried with Pycharm, adding a Fortran plugin.

Please, anny suggestion the fix this problem in my computer?

Thank you for your attention.

**Comment by mattcieslak** [comment]
Have you followed this section in the readme?

### Adding Geometric Constraints (optional)

Download the current version of MITTENS and enter its source tree:

```bash
$ git clone https://github.com/mattcieslak/MITTENS.git
$ cd MITTENS
```

Now, launch a python session in the mittens directory

```python
>>> from mittens.write_solution import write_solution
>>> write_solution("odf8", 35, 1.0)
```

This will write out two fortran files in the current directory. They are named
after the parameters you chose. This particular example will read data
reconstructed with 8-fold ODF tesselation, a turning angle maximum of 35
degrees and a step size of 1.0 voxel units (voxels are assumed to be
isotropic).

After some calculations you will find
``doubleODF_odf8_ss1_00_am35.f90`` and ``singleODF_odf8_ss1_00_am35.f90``
in the current directory. Move these files into the ``src/`` directory
and install the package with ``pip``. We recommend using an editable
install, which will keep all these files in their current directory:

```bash
mv *.f90 src/
pip install -e .
```

This will compile everything in the ``src/`` directory into a
python module. You can now use these geometric constraints to
calculate transition expectations.

**Comment by dubergonzoni** [comment]
I can't import "write_solution" as described in this readme section:

>>> from mittens.write_solution import write_solution
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'write_solution' from 'mittens.write_solution' (/home/edu_asus/Documentos/Research/MITTENS/mittens/write_solution.py)

I just realized that the second "write_solution" should be "write_files". There is no "write_solution" function inside "write_solution.py" module.

For this reason, I was trying to run "pip install -e ." just with the .f90 files examples in the /src folder.
But now I could start to create the new .f90 files. Probably it will work.

>>> from mittens.write_solution import write_files

>>> write_files("odf8", 35, 1.0)
  0%|                                                    | 0/26 [00:00<?, ?it/s]

I will let you know if the code is working after creating these files, as described in the readme.
Thank you.

**Comment by dubergonzoni** [comment]
@mattcieslak 

I could install with pip of my system, after disabling conda and pyenv environments.

Thank you so much for your help and patience.

Sincerely,
Eduardo
